#!/bin/bash

echo "╔══════════════════════════════════╗"
echo "║         KubeOne Workshop         ║"
echo "╚══════════════════════════════════╝"
echo ""
echo "tools:"
echo "  kubectl   $(kubectl version --client --output=yaml 2>/dev/null | grep gitVersion | awk '{print $2}')"
echo "  krew      $(kubectl krew version 2>/dev/null | grep GitTag | awk '{print $2}')"
echo "  helm      $(helm version --short 2>/dev/null)"
echo "  helmfile  $(helmfile version -o=short 2>/dev/null)"
echo "  kubectx   $(kubectx --version 2>/dev/null)"
echo "  gcloud    $(gcloud version --format="value('Google Cloud SDK')" 2>/dev/null)"
echo "  terraform $(terraform version 2>/dev/null | head -1 | awk '{print $2}')"
echo "  velero    $(velero version --client-only 2>/dev/null | awk '/Version:/{print $2; exit}')"
echo "  zsh       $(zsh --version 2>/dev/null | awk '{print $2}')"
echo ""
# echo "kubeconfig: ${KUBECONFIG}"
echo ""
