apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    cluster.k8s.io/cluster-api-autoscaler-node-group-max-size: "3"
    cluster.k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
    k8c.io/operating-system-profile: ""
  name: hubert-04-cluster-europe-west3-a
  namespace: kube-system
spec:
  minReadySeconds: 0
  replicas: 1
  selector:
    matchLabels:
      workerset: hubert-04-cluster-europe-west3-a
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workerset: hubert-04-cluster-europe-west3-a
      namespace: kube-system
    spec:
      metadata:
        labels:
          workerset: hubert-04-cluster-europe-west3-a
      providerSpec:
        value:
          cloudProvider: gce
          cloudProviderSpec:
            assignPublicIPAddress: true
            diskSize: 20
            diskType: pd-standard
            labels:
              hubert-04-cluster-workers: europe-west3-a
            machineType: n1-standard-1
            multizone: true
            network: https://www.googleapis.com/compute/v1/projects/k1-del-codespaces/global/networks/default
            preemptible: false
            regional: false
            subnetwork: https://www.googleapis.com/compute/v1/projects/k1-del-codespaces/regions/europe-west3/subnetworks/default
            tags:
            - firewall
            - targets
            - hubert-04-cluster-europe-west3-a
            zone: europe-west3-a
          operatingSystem: ubuntu
          operatingSystemSpec:
            distUpgradeOnBoot: true
          sshPublicKeys:
          - |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvs5SHpkJ0pYnHff6UkUYafFDIxsgNefNni91RO5AguxB44/jng55VZyRk0t0hTvo0eQX2RElUvKK7BMn6aY39YXSn2GGIfJ145D53xIG3NYZKryVdLa4wlEB00KgSexQOUA3Y4/pq18bNQU7KgoxK2KQ15t3ELjbKtPVzPOXOqy+r5ubUNKNsE+3NfRCSKlHV/2/vsur4lGFBYHJUPJIgU40nwiFBf+DeWigbD6ZK1lt0fZFt8FOsN0ndKhNCRte77DqLExMSXBacV8NC6c4RPiL1i7UHWNQnuyqMj1Hr+sI9tUcgib+JDYbycrL8oY30VYLhTwEziB83bsrGNDUEoFj1yb0ffRyq6E+7I3+cmMiOrlANjhpPPDprrBlhlaWOH+tsuXRj4SErDy1eH9YKt7RA/ddG0xcZXwjCMh0GtGx95vzDShRXVLExwvnMR7DM30LAmEy7b2wDW6djk+82NwiwwiXuj98ik57c6ml+DAVcKQYaT+d2ouHTc0O1X2k= root
      versions:
        kubelet: 1.36.3
status: {}

---

