apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
        - name: my-app-container
          image: quay.io/kubermatic-labs/training-application:4.0.0
          imagePullPolicy: Always
          tty: true
          stdin: true
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: my-volume
              mountPath: /app/training-application.conf
              subPath: training-application.conf
      volumes:
        - name: my-volume
          configMap:
            name: my-configmap
